required_devices: 8
resume: false

no_test: false
test_only: false
debug: false
seed: 0
distributed: false
test_freq: 5
num_workers: 32

benchmark:
  name: "hmdb51-wucls-32at16"

dataset:
  name: "hmdb51"
  fold: 3
  batch_size: 32
  clip_duration: 2.
  video_fps: 16.
  transform: "msc+color"
  crop_size: 224
  min_area: 0.08
  color: [1., 1., 1., 0.2]
  train:
    split: "train-split{fold}"
    mode: "clip"
    clips_per_video: 10
    use_augmentation: true
    use_shuffle: true
    drop_last: true
  test:
    split: "test-split{fold}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "test-split{fold}"
    mode: "video"
    clips_per_video: 10
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 10
  weight_decay: 0.0
  warmup_classifier: true
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 0.3
    milestones: [3, 6, 8]

model:
  name: "ClassificationWrapper"
  args:
    n_classes: 51
    feat_name: "pool"
    pooling_op: null
    feat_dim: 512
    use_dropout: true
    dropout: 0.5
